version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - cms-overlay

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - cms-overlay

  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: mongo-db
      DATABASE_USER: root
      DATABASE_PASSWORD: example
    networks:
      - cms-overlay

networks:
  cms-overlay:
    external:
      name: cms-overlay